name: Resources
on: repository_dispatch
jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.action }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Fetch resources
        run: npx tsx ./index.ts $VERSION

      - name: Update resources
        uses: test-room-7/action-update-file@v2
        with:
          file-path: resources/connectors.json
          commit-msg: |
            Update resources

            Update connectors.json to match ${{ github.event.action }} version.
          github-token: ${{ secrets.GITHUB_TOKEN }}
